languageCode = "en"
languageName = "English"
weight = 1
title = "Higher Education Cyber Challenge"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "A cyber competition and networking event for UK universities"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[author]
  name = "Higher Education Cyber Challenge"
  image = "img/avatar.png"
  headline = "A cyber competition and networking event for UK university students"
  bio = "A little bit about you"
   links = [
     { link = "https://hecc.ecs.soton.ac.uk/" },
     { github = "https://github.com/hecctf" },
     { x-twitter = "https://twitter.com/hecctf" }
   ]
